baseURL = "/"
languageCode = "es"
title = "Sistema de Comentarios Networking"
disableKinds = ["taxonomy", "term"]

[params]
  description = "Deja tus comentarios sobre nuestras herramientas de networking"
  author = "Networking Professional"
  mainImage = "https://cdn.pixabay.com/photo/2014/04/03/10/32/chat-312557_960_720.png"
  favicon = "https://cdn.pixabay.com/photo/2013/07/12/17/45/speech-bubble-152023_960_720.png"
  mainSiteURL = "https://test-indice.netlify.app"
