baseURL = "/"
languageCode = "es"
title = "Sistema de Comentarios Networking"
disableKinds = ["taxonomy", "term"]

[params]
  description = "Deja tus comentarios sobre nuestras herramientas de networking"
  author = "Networking Professional"
  mainImage = "/images/chat-icon.svg"
  favicon = "/images/favicon-bubble.svg"
  mainSiteURL = "https://test-indice.netlify.app"
